postsPerPage = 10
baseUrl = "https://ditari.eltonkola.com"

websiteName = "Ditari i Gjergj Kastriotit"
websiteDescription = "Një vit jetë nga ditari i Dragoit të Arbërit"

feedEmail = "eltonkola@gmail.com"
feedEmailRealName = "Elton Kola"

socials = ["http://eltonkola.com", "https://github.com/eltonkola/bllok/"]

copyright = "2025 eKola"
language = "sq"