postsPerPage = 10
baseUrl = "https://localhost:8000"

websiteName = "eltonKola"
websiteDescription = "random thoughts from a dev's life"

feedEmail = "eltonkola@gmail.com"
feedEmailRealName = "Elton Kola"

socials = ["http://eltonkola.com", "https://github.com/eltonkola/bllok/"]

copyright = "Made with ❤️ by Elton Kola ©"
language = "en-US"