postsPerPage = 10
baseUrl = "https://localhost:8000"

websiteName = "Letersia shqiptare"
websiteDescription = "Letersia nga fajtori web"

feedEmail = "eltonkola@gmail.com"
feedEmailRealName = "Elton Kola"

socials = ["http://eltonkola.com", "https://github.com/eltonkola/bllok/"]

copyright = "2025 eKola"
language = "sq"